name: Release

on:
  push:
    branches:
      - 'release-test*'  # Only run on branches with release-test prefix

permissions:
  contents: read

jobs:
  # Use the reusable trusted tag workflow for releases if approved
  release:
    concurrency:
      group: "release"
      cancel-in-progress: false
    permissions:
      id-token: write    # Required for SLSA provenance
      contents: write    # Required for release and tag creation
      pull-requests: write # Required for bumpr commenting
      actions: read      # Required for SLSA generator
      attestations: write # Required for build provenance attestation
    uses: actionutils/trusted-tag-releaser/.github/workflows/trusted-release-workflow.yml@97770210d429b848cbafdd6f70cf85205034b858
    with:
      environment: release
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
